version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banky
      MYSQL_USER: banky
      MYSQL_PASSWORD: banky
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
