INSERT INTO bky_category (id, name)
VALUES
    (1, 'Épargne'),
    (2, 'Abonnement'),
    (3, 'Logement & Charges'),
    (4, 'Assurances'),
    (5, 'Culture & Sport'),
    (6, 'Voyages'),
    (7, 'Santé & Bien-être'),
    (8, 'Vêtements'),
    (9, 'Divers'),
    (10, 'Alimentaire'),
    (11, 'Impôts & Amendes'),
    (12, 'Revenus'),
    (13, 'Frais Bancaires'),
    (14, 'Voiture & Vélo')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO bky_sub_category (id, name, category_id)
VALUES
    (1, 'Abondement', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (2, 'Abonnement Internet', (SELECT id FROM bky_category WHERE name = 'Abonnement')),
    (3, 'Abonnement Téléphone', (SELECT id FROM bky_category WHERE name = 'Abonnement')),
    (4, 'Abonnement Netflix', (SELECT id FROM bky_category WHERE name = 'Abonnement')),
    (5, 'Abonnement électricité', (SELECT id FROM bky_category WHERE name = 'Logement & Charges')),
    (6, 'Accidents de la Vie', (SELECT id FROM bky_category WHERE name = 'Assurances')),
    (7, 'Achat Appartement', (SELECT id FROM bky_category WHERE name = 'Logement & Charges')),
    (8, 'Adhésions', (SELECT id FROM bky_category WHERE name = 'Culture & Sport')),
    (9, 'Assurance santé', (SELECT id FROM bky_category WHERE name = 'Assurances')),
    (10, 'Assurance habitation', (SELECT id FROM bky_category WHERE name = 'Assurances')),
    (11, 'Avion', (SELECT id FROM bky_category WHERE name = 'Voyages')),
    (12, 'Bijoux', (SELECT id FROM bky_category WHERE name = 'Santé & Bien-être')),
    (13, 'Cadeaux & Dons', (SELECT id FROM bky_category WHERE name = 'Culture & Sport')),
    (14, 'Chaussures', (SELECT id FROM bky_category WHERE name = 'Vêtements')),
    (15, 'Compte Courant', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (16, 'Courrier', (SELECT id FROM bky_category WHERE name = 'Divers')),
    (17, 'Cinéma', (SELECT id FROM bky_category WHERE name = 'Culture & Sport')),
    (18, 'Coiffeur', (SELECT id FROM bky_category WHERE name = 'Santé & Bien-être')),
    (19, 'Course', (SELECT id FROM bky_category WHERE name = 'Alimentaire')),
    (20, 'Divers', (SELECT id FROM bky_category WHERE name = 'Divers')),
    (21, 'Dividendes', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (22, 'Électroménager', (SELECT id FROM bky_category WHERE name = 'Logement & Charges')),
    (23, 'Équilibrage', (SELECT id FROM bky_category WHERE name = 'Divers')),
    (24, 'Hôtel', (SELECT id FROM bky_category WHERE name = 'Voyages')),
    (25, 'Informatique', (SELECT id FROM bky_category WHERE name = 'Culture & Sport')),
    (26, 'Impôts', (SELECT id FROM bky_category WHERE name = 'Impôts & Amendes')),
    (27, 'Intérêts', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (28, 'Jeux Vidéos', (SELECT id FROM bky_category WHERE name = 'Culture & Sport')),
    (29, 'Loisir', (SELECT id FROM bky_category WHERE name = 'Culture & Sport')),
    (30, 'Livres', (SELECT id FROM bky_category WHERE name = 'Culture & Sport')),
    (31, 'Livret A', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (32, 'Livret Jeune', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (33, 'Linxea Avenir 2', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (34, 'Linxea Spirit 2', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (35, 'LLDS', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (36, 'PEA', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (37, 'Loyer', (SELECT id FROM bky_category WHERE name = 'Logement & Charges')),
    (38, 'Médecin', (SELECT id FROM bky_category WHERE name = 'Santé & Bien-être')),
    (39, 'Médicaments', (SELECT id FROM bky_category WHERE name = 'Santé & Bien-être')),
    (40, 'Meubles & Mobilier', (SELECT id FROM bky_category WHERE name = 'Logement & Charges')),
    (41, 'Musée & simili', (SELECT id FROM bky_category WHERE name = 'Culture & Sport')),
    (42, 'Musique', (SELECT id FROM bky_category WHERE name = 'Culture & Sport')),
    (43, 'Navigo', (SELECT id FROM bky_category WHERE name = 'Voyages')),
    (44, 'Notes de Frais', (SELECT id FROM bky_category WHERE name = 'Revenus')),
    (45, 'Nourriture', (SELECT id FROM bky_category WHERE name = 'Alimentaire')),
    (46, 'Ouverture Compte', (SELECT id FROM bky_category WHERE name = 'Frais Bancaires')),
    (47, 'Parking', (SELECT id FROM bky_category WHERE name = 'Voiture & Vélo')),
    (48, 'Péage', (SELECT id FROM bky_category WHERE name = 'Voiture & Vélo')),
    (49, 'Pharmacie', (SELECT id FROM bky_category WHERE name = 'Santé & Bien-être')),
    (50, 'PV Stationnement', (SELECT id FROM bky_category WHERE name = 'Impôts & Amendes')),
    (51, 'PV Transports', (SELECT id FROM bky_category WHERE name = 'Impôts & Amendes')),
    (52, 'Remboursement', (SELECT id FROM bky_category WHERE name = 'Divers')),
    (53, 'Repas', (SELECT id FROM bky_category WHERE name = 'Alimentaire')),
    (54, 'Restaurant & Bar', (SELECT id FROM bky_category WHERE name = 'Alimentaire')),
    (55, 'Retrait ATM', (SELECT id FROM bky_category WHERE name = 'Divers')),
    (56, 'Salaire', (SELECT id FROM bky_category WHERE name = 'Revenus')),
    (57, 'Soirée', (SELECT id FROM bky_category WHERE name = 'Alimentaire')),
    (58, 'Spectacle', (SELECT id FROM bky_category WHERE name = 'Culture & Sport')),
    (59, 'Taxe d habitation & Redevance audio-visuelle', (SELECT id FROM bky_category WHERE name = 'Impôts & Amendes')),
    (60, 'Taxe foncière & Enlèvement Ordures', (SELECT id FROM bky_category WHERE name = 'Impôts & Amendes')),
    (61, 'Tenue de Compte', (SELECT id FROM bky_category WHERE name = 'Frais Bancaires')),
    (62, 'Ticket Restaurant', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (63, 'Train', (SELECT id FROM bky_category WHERE name = 'Voyages')),
    (64, 'Transports en commun', (SELECT id FROM bky_category WHERE name = 'Voyages')),
    (65, 'Travaux', (SELECT id FROM bky_category WHERE name = 'Logement & Charges')),
    (66, 'Vêtements', (SELECT id FROM bky_category WHERE name = 'Vêtements')),
    (67, 'Vente', (SELECT id FROM bky_category WHERE name = 'Revenus')),
    (68, 'Virement', (SELECT id FROM bky_category WHERE name = 'Épargne')),
    (69, 'Voiture', (SELECT id FROM bky_category WHERE name = 'Voyages')),
    (70, 'Vélo', (SELECT id FROM bky_category WHERE name = 'Voyages'))
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO bky_accounts (id, name, short_name, color, initial_amount, type)
VALUES (1, 'Crédit Agricole', 'CA', '008A91', 0.00, 'CHECKING'),
       (2, 'Portefeuille', 'PF', '000000', 0.00, 'CHECKING'),
       (3, 'Ticket Restaurant', 'TR', 'FF6200', 0.00, 'CHECKING'),
       (4, 'Carte Cadeaux', 'CC', 'E2010F', 0.00, 'CHECKING'),
       (5, 'Fortuneo', 'FTO', '5865F2', 0.00, 'CHECKING'),
       (6, 'Livret A', 'LA', '1E90FF', 0.00, 'SAVINGS'),
       (7, 'Livret Jeune', 'LJ', '32CD32', 0.00, 'SAVINGS'),
       (8, 'Linxea Avenir 2', 'LA2', 'FFA500', 0.00, 'MARKET'),
       (9, 'Linxea Spirit 2', 'LS2', 'FF1493', 0.00, 'MARKET'),
       (10, 'LLDS', 'LDS', '8B0000', 0.00, 'SAVINGS'),
       (11, 'PEA', 'PEA', '4682B4', 0.00, 'MARKET'),
       (12, 'CTO', 'CTO', '4682B4', 0.00, 'MARKET');